Web/Controllers/TipoActivoController.cs
using ApplicationCore.Services;
using Infraestructure.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Web.Security;
using Web.Utils;

namespace Web.Controllers
{
    public class TipoActivoController : Controller
    {
        protected static String Action;

        // GET: TipoActivo
        [CustomAuthorizeAttribute((int)Roles.Administrador, (int)Roles.Proceso)]
        public ActionResult Index()
        {
            try
            {
                return RedirectToAction("List");//llama al metodo List() y lo direcciona

            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                // Pasar el Error a la página que lo muestra
                TempData["Message"] = ex.Message;
                TempData.Keep();
                return RedirectToAction("Default", "Error");
            }
        }

        [CustomAuthorizeAttribute((int)Roles.Administrador, (int)Roles.Proceso)]
        public ActionResult List()
        {
            IEnumerable<TipoActivo> lista = null;
            try
            {
                Log.Info("Visita");//manda un mensaje de entrada para documentar en el log

                //hace una instancia del servidor y obtiene una lista de los vendedores
                IServiceTipoActivo _ServiceTipoActivo = new ServiceTipoActivo();
                lista = _ServiceTipoActivo.GetTipoActivo();

                if (!String.IsNullOrEmpty(Action))
                {
                    ViewBag.Action = Action;

                }
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());

                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }

            return View(lista);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorizeAttribute((int)Roles.Administrador, (int)Roles.Proceso)]
        public ActionResult Save(TipoActivo tipo)
        {
            string errores = "";
            try
            {
                // Es valido
                if (ModelState.IsValid)
                {   //hace una instancia del servidor y actualiza o crea un vendedor
                    IServiceTipoActivo _ServiceTipoActivo = new ServiceTipoActivo();
                    if (_ServiceTipoActivo.Save(tipo))
                        Action = "S";
                    else
                        Action = "U";
                }
                else
                {
                    // Valida Errores si Javascript está deshabilitado
                    Util.ValidateErrors(this);

                    TempData["Message"] = "Error al procesar los datos! " + errores;
                    TempData.Keep();
                    return View("Create", tipo);
                }

                // redirigir
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }

        // GET: TipoActivo/Details/5
        [CustomAuthorizeAttribute((int)Roles.Administrador, (int)Roles.Proceso)]
        public ActionResult Details(int id)
        {
            IServiceTipoActivo _ServiceTipoActivo = new ServiceTipoActivo();
            TipoActivo tipo = null;

            try
            {
                // Si va null
                if (id <= 0)
                {
                    ViewBag.Error = "Problemas a encontrar el codigo";
                    return View();
                }
                //obtiene el vendedor segun su cedula
                tipo = _ServiceTipoActivo.GetTipoActivoByID(id);

                return PartialView("_DetalleTipoActivo", tipo);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                Action = "E";
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }

        // GET: TipoActivo/Edit/5
        [CustomAuthorizeAttribute((int)Roles.Administrador, (int)Roles.Proceso)]
        public ActionResult Edit(int id)
        {
            IServiceTipoActivo _ServiceTipoActivo = new ServiceTipoActivo();
            TipoActivo tipo = null;
            try
            {
                // Si va null
                if (id <= 0)
                {
                    return RedirectToAction("List");
                }

                tipo = _ServiceTipoActivo.GetTipoActivoByID(id);
                // Response.StatusCode = 500;
                return View(tipo);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                Action = "E";
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }

        // GET: TipoActivo/Create
        [CustomAuthorizeAttribute((int)Roles.Administrador, (int)Roles.Proceso)]
        public ActionResult Create()
        {
            return View();
        }

        // GET: TipoActivo/Delete/5
        [CustomAuthorizeAttribute((int)Roles.Administrador, (int)Roles.Proceso)]
        public ActionResult Delete(int id)
        {
            try
            {
                // Si va null
                if (id <= 0)
                {
                    return RedirectToAction("List");
                }


                List<Activo> listaAct = new List<Activo>();
                IServiceActivo service = new ServiceActivo();
                listaAct = (List<Activo>)service.GetActivo();

                if (listaAct != null)
                {
                    foreach (Activo act in listaAct)
                    {
                        if (act.idTipoActivo == id)
                        {
                            TempData["Message"] = "No se puede eliminar, el tipo de activo ha sido asignado a un activo";
                            TempData.Keep();
                            Action = "E";
                            return RedirectToAction("List");
                        }
                    }

                }

                IServiceTipoActivo _ServiceTipoActivo = new ServiceTipoActivo();
                TipoActivo tipo = _ServiceTipoActivo.GetTipoActivoByID(id);

                return View(tipo);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                Action = "E";
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorizeAttribute((int)Roles.Administrador, (int)Roles.Proceso)]
        public ActionResult DeleteConfirmed(int id)
        {
            IServiceTipoActivo _ServiceTipoActivo = new ServiceTipoActivo();

            try
            {

                if (id <= 0)
                {
                    return View();
                }

                _ServiceTipoActivo.DeleteTipoActivo(id);
                Action = "D";
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                Action = "E";
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }

        [ChildActionOnly]
        public ActionResult GetTipoActById(int id)
        {
            IServiceTipoActivo service = new ServiceTipoActivo();
            TipoActivo oTipo = service.GetTipoActivoByID(id);

            return Content(oTipo.idTipoActivo + " - " + oTipo.descripcion);
        }
    }
}

Web/Views/TipoActivo/Create.cshtml
@model Infraestructure.Models.TipoActivo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Save", "TipoActivo", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TipoActivo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create"  class="btn  btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web/Views/TipoActivo/Delete.cshtml
@model Infraestructure.Models.TipoActivo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h4>TipoActivo</h4>
<hr />
@using (Html.BeginForm("DeleteConfirmed", "TipoActivo"))
{
    @Html.AntiForgeryToken()
    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.idTipoActivo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.idTipoActivo)
                @Html.Hidden("id", Model.idTipoActivo)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.descripcion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.descripcion)
            </dd>

        </dl>
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn  btn-danger btn-md "/> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
}

Web/Views/TipoActivo/Edit.cshtml
@model Infraestructure.Models.TipoActivo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<h2>Edit</h2>


@using (Html.BeginForm("Save", "TipoActivo", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>TipoActivo</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.idTipoActivo)

    <div class="form-group">
        @Html.LabelFor(model => model.idTipoActivo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.idTipoActivo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.idTipoActivo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn  btn-success" />
        </div>
    </div>

</div>
   }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

Web/Views/TipoActivo/List.cshtml
@model IEnumerable<Infraestructure.Models.TipoActivo>

@{
    ViewBag.Title = "List";
}

<h2>Tipo de Activo</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@if (TempData["Message"] != null)
{
    string mensaje = @"<div class='alert alert-danger alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'>
<span aria-hidden='true'>&times;</span> </button><strong>Error!</strong> " + TempData["Message"] + " </div>";
@Html.Raw(mensaje);
}
<table class="table table-hover table-striped ">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.idTipoActivo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.descripcion)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.idTipoActivo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descripcion)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.idTipoActivo }, new { @class = "btn  btn-primary btn-md " })
                <a onclick="modalDetail(@item.idTipoActivo)" class="btn btn-warning btn-md" href="#">Details</a>
                @Html.ActionLink("Delete", "Delete", new { id = item.idTipoActivo }, new { @class = "btn  btn-danger btn-md " })
            </td>
        </tr>
    }

</table>
<input type="hidden" id="campoOculto" />

<!-- Modal -->
<!--Las ventanas modals estan ocultas en el código son activadas por Javascript/JQuery-->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Detalle del Tipo de Activo</h4>
            </div>
            <div class="modal-body">
                @ViewBag.Error
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/toastjs")
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqueryui")

    <script>

        $(document).ready(function () {
                console.log("Entro a JQuery")

            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": false,
                "progressBar": true,
                "positionClass": "toast-top-right",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "500",
                "hideDuration": "1000",
                "timeOut": "1200",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            }

                // Recibe los parámetros del Controller
                var option = '@ViewBag.Action'


                if (option == 'S') {
                    toastr["success"]("Creado con exito!", "Save");
                }


                 if (option == 'D') {
                     toastr["warning"]("Eliminado con exito!", "Delete")
                }


                 if (option == 'U') {
                     toastr["info"]("Actualizado con exito!", "Update")
                }

            if (option == 'E') {
                toastr["error"]("Se ha producido un error ", "Error")
            }

           
        });

    </script>

    <script>
        function modalDetail(p) {
            // Almacena el Id del estudiante en el hidden field tipo variable global
            $("#campoOculto").val(p);
            // $("#myModal").val(p);
            //var temp = $("#campoOculto").val();
            // Invoca al Div de Modal de una vez se invoca el evento shown.bs.modal
            // donde se invoca al Ajax con el Partial View
            $("#myModal").modal();
        }
    </script>



    <script>
        debugger;
        // Este evento se ejecuta antes después de invocar  $("#myModal").modal();
        // acá es donde se invoca por Ajax al Controller y este devuelve Partial View
        $('#myModal').on('shown.bs.modal', function () {
            // permite mover
            $('.modal-dialog').draggable();
            // Se lee el campo oculto
            var idT = $("#campoOculto").val();
            //var identificacionEstudiante = $("#myModal").val();
            console.log(idT);
            $.ajax({
                type: "GET",
                url: "/TipoActivo/Details/",
                // parametro por JSON
                data: { id: idT },
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    $(".modal-body").html(data);
                },
                // Capturar errores y mostrar un mensaje de error
                error: function (xhr, status, error) {
                    var mensaje = "<div class='alert alert-danger' role='alert'> Result: " +
                        status + " " + error + " " + xhr.status + " " + xhr.statusText + "</div>";
                    //debugger;
                    $("#mensaje").html(mensaje).show("slow").delay(1000).hide("slow");
                }
            });

        })

        // Se ejecuta cuando se destruye el modal
        $("#myModal").on('hide.bs.modal', function () {
            // Se limpia el Div para no dejar
            $(".modal-body").html("...");
        });

    </script>

}

Web/Views/TipoActivo/_DetalleTipoActivo.cshtml
@model Infraestructure.Models.TipoActivo

<div>
    <h4>Tipo Activo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.idTipoActivo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idTipoActivo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

    </dl>
</div>