Web/Controllers/ActivoController.cs
using ApplicationCore.Services;
using Infraestructure.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Web.Models;
using Web.Security;
using Web.Utils;

namespace Web.Controllers
{
    public class ActivoController : Controller
    {
        protected static String Action="";
        // GET: Activo
        [CustomAuthorizeAttribute((int)Roles.Administrador, (int)Roles.Proceso)]
        public ActionResult Index()
        {
            try
            {
                return RedirectToAction("List");//llama al metodo List() y lo direcciona

            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                // Pasar el Error a la página que lo muestra
                TempData["Message"] = ex.Message;
                TempData.Keep();
                return RedirectToAction("Default", "Error");
            }
        }

        [CustomAuthorizeAttribute((int)Roles.Administrador, (int)Roles.Proceso)]
        public ActionResult List()
        {
            IEnumerable<Activo> lista = null;
            try
            {
                Log.Info("Visita");//manda un mensaje de entrada para documentar en el log

                //hace una instancia del servidor y obtiene una lista de las marcas
                IServiceActivo _ServiceActivo = new ServiceActivo();
                lista = _ServiceActivo.GetActivo();

                if (!String.IsNullOrEmpty(Action))
                {
                    ViewBag.Action = Action;

                }
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());

                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }

            return View(lista);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorizeAttribute((int)Roles.Administrador, (int)Roles.Proceso)]
        public ActionResult Save(Activo activo, HttpPostedFileBase ImageFileFact, HttpPostedFileBase ImageFileA)
        {
            string errores = "";
            MemoryStream target = new MemoryStream();
            MemoryStream target1 = new MemoryStream();//ultimo cambio
            try
            {
                // Cuando es Insert Image viene en null porque se pasa diferente
               
                    if (ImageFileFact != null)
                    {
                        ImageFileFact.InputStream.CopyTo(target);
                        activo.fotoFactura = target.ToArray();
                        ModelState.Remove("ImageFileFact");
                    }
                    /*else
                    {
                        TempData["Message"] = "No ingreso una imagen de la Factura" + errores;
                        TempData.Keep();
                        return View("Create", activo);
                    }*/

                    if (ImageFileA != null)
                    {
                        ImageFileA.InputStream.CopyTo(target1);
                        activo.fotoActivo = target1.ToArray();
                        ModelState.Remove("ImageFileA");

                    }
                  /*  else
                    {
                        TempData["Message"] = "No ingreso una imagen del activo" + errores;
                        TempData.Keep();
                        return View("Create", activo);
                    }*/


             //   activo.idMarca = txtIdMarca;
                // Es valido
               if (ModelState.IsValid)
                {
                    //hace una instancia del servidor y actualiza o crea una marca
                    IServiceActivo _ServiceActivo = new ServiceActivo();
                  
                    if (activo.precioActual == null)
                         activo.precioActual = activo.precioColones;

                    ServiceBCCR service = new ServiceBCCR();
                        activo.precioDolares = service.GetDolar(activo.precioColones);
                  //  }
                  
                    if (_ServiceActivo.Save(activo))
                        Action = "S";
                    else
                        Action = "U";
                }
                else
                {
                    // Valida Errores si Javascript está deshabilitado
                    Util.ValidateErrors(this);

                    TempData["Message"] = "Error al procesar los datos! " + errores;
                    TempData.Keep();
                    return View("Create", activo);
                }

                // redirigir
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }

        // GET: Marca/Details/5
        [CustomAuthorizeAttribute((int)Roles.Administrador, (int)Roles.Proceso)]
        public ActionResult Details(int id)
        {
            IServiceActivo _ServiceActivo = new ServiceActivo();
            Activo activo = null;

            try
            {
                // Si va null
                if (id <= 0)
                {
                    ViewBag.Error = "Problemas a encontrar el codigo";
                    return View();
                }
                //obtiene la marca según su id
                activo = _ServiceActivo.GetActivoByID(id);

                return PartialView("_DetalleActivo", activo);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                Action = "E";
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }

        // GET: Marca/Edit/5
        [CustomAuthorizeAttribute((int)Roles.Administrador, (int)Roles.Proceso)]
        public ActionResult Edit(int id)
        {
            IServiceActivo _ServiceActivo = new ServiceActivo();
            Activo act = null;
            try
            {
                // Si va null
                if (id <= 0)
                {
                    return RedirectToAction("List");
                }
                IServiceAsegurado service = new ServiceAsegurado();
                ViewBag.ListaAsegurado = service.GetAsegurado();

                IServiceTipoActivo serviceT = new ServiceTipoActivo();
                ViewBag.ListaTipo = serviceT.GetTipoActivo();

                act = _ServiceActivo.GetActivoByID(id);

             //   int txtIdMarca = act.idMarca;
                // Response.StatusCode = 500;
                return View(act);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                Action = "E";
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }

        // GET: Marca/Create
        [CustomAuthorizeAttribute((int)Roles.Administrador, (int)Roles.Proceso)]
        public ActionResult Create()
        {
            IServiceAsegurado service = new ServiceAsegurado();
            ViewBag.ListaAsegurado= service.GetAsegurado();

            IServiceTipoActivo serviceT = new ServiceTipoActivo();
            ViewBag.ListaTipo = serviceT.GetTipoActivo();

            return View();
        }

        // GET: Marca/Delete/5
        [CustomAuthorizeAttribute((int)Roles.Administrador, (int)Roles.Proceso)]
        public ActionResult Delete(int id)
        {
            try
            {
                // Si va null
                if (id <= 0)
                {
                    return RedirectToAction("List");
                }

                IServiceActivo _ServiceActivo = new ServiceActivo();
                Activo act = _ServiceActivo.GetActivoByID(id);

                return View(act);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                Action = "E";
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorizeAttribute((int)Roles.Administrador, (int)Roles.Proceso)]
        public ActionResult DeleteConfirmed(int id)
        {
            IServiceActivo _ServiceActivo = new ServiceActivo();

            try
            {

                if (id <=0)
                {
                    return View();
                }

                _ServiceActivo.DeleteActivo(id);
                Action = "D";
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());

Web/Views/Activo/Create.cshtml
@model Infraestructure.Models.Activo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Save", "Activo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Activo</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.numSerie, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.numSerie, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.numSerie, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.idTipoActivo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("idTipoActivo", new SelectList(ViewBag.ListaTipo, "idTipoActivo", "descripcion"), htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idTipoActivo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.vidaUtil, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.vidaUtil, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.vidaUtil, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.modelo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.modelo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.modelo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.fechaCompra, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.fechaCompra, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.fechaCompra, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.precioColones, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.precioColones, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.precioColones, "", new { @class = "text-danger" })
        </div>
    </div>

    @* <div class="form-group">
            @Html.LabelFor(model => model.precioDolares, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precioDolares, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precioDolares, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.fechaVenceGarantia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.fechaVenceGarantia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.fechaVenceGarantia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.fechaVenceSeguro, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.fechaVenceSeguro, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.fechaVenceSeguro, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <ul style="list-style:none">
                <li> Excelente @Html.RadioButtonFor(model => model.estado, "Excelente", false)</li>
                <li> Bueno @Html.RadioButtonFor(model => model.estado, "Bueno", false)</li>
                <li> Regular @Html.RadioButtonFor(model => model.estado, "Regular", false)</li>
                <li> Malo @Html.RadioButtonFor(model => model.estado, "Malo", false)</li>
            </ul>
            @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.fotoFactura, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFileFact" required />
            @* @Html.EditorFor(model => model.fotoFactura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fotoFactura, "", new { @class = "text-danger" })*@
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.fotoActivo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFileA" required />
            @* @Html.EditorFor(model => model.fotoActivo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fotoActivo, "", new { @class = "text-danger" })*@
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            @Html.Label("Marca", htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.TextBoxFor(model => model.idMarca, new { @class = "form-control", @id="idMarca" })
            @Html.Label("txtDescripcion", "-", htmlAttributes: new { @class = "control-label col-md-2" })

            @*
        @Html.HiddenFor(model => model.idMarca);
        @Html.EditorFor(model => model.idMarca, new { htmlAttributes = new { @class = "form-control", @attribute = "data-codigo" } })
        @Html.Label("Marca", "*")
        @Html.ValidationMessageFor(model => model.idMarca, "", new { @class = "text-danger" })*@
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.idAsegurado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("idAsegurado", new SelectList(ViewBag.ListaAsegurado, "idAsegurado", "descripcion"), htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idAsegurado, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.cedVendedor, "Vendedor", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.cedVendedor, new { htmlAttributes = new { @class = "form-control", @attribute = "data-codigo" } })
            @Html.Label("IdVendedor", "*")
            @Html.ValidationMessageFor(model => model.cedVendedor, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn  btn-success" data-toggle="tooltip" data-placement="top" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqueryui")

    <script>
        // Habilita los tooltips
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>

    <script>
        ////////////////////////////////////////////////////
        // Busca el Marca                                  //
        /////////////////////////////////////////////////////
        $("#idMarca").focus(function () {
            // Limpia la caja de texto
            $("#idMarca").val("");
            console.log($("label[for*='txtDescripcion']").html());
            $("label[for*='txtDescripcion']").html("-");
        });

        $("#idMarca").autocomplete({
            source: function (request, response) {
                var texto = $("#idMarca").val();
                debugger;
                console.log(texto);
                $.ajax({
                    type: "GET",
                    url: "/Marca/GetMarcaByName",
                    dataType: "json",
                    data: { name: texto },
                    success: function (data) {
                        response($.map(data, function (item) {
                            console.log(item.descripcion);
                            //debugger;
                            return { label: item.descripcion, value: item.idMarca };
                        }));
                    },
                    error: function (xhr, status, error) {
                        // xhr.requestText
                        // debugger;
                        alert("Error: " + error + ", No Error: " + xhr.status);
                    },
                });
            },
            select: function (event, ui) {

                // Colocar el valor
                $("#idMarca").val(ui.item.value);
                // Coloca datos en el Label
                $("label[for*='txtDescripcion']").html(ui.item.label);
                return false;
            }, statusCode: {
                404: function (content) { alert('cannot find resource'); },
                500: function (content) { alert('internal server error'); }
            },
            error: function (xhr, status, error) {
                // Muestra posibles errores
                alert("Error: " + error + ", No Error: " + xhr.status);
            }
        });
    </script>


    <script>
        ////////////////////////////////////////////////////
        // Busca el cliente por nombre+apellido1+apellido2 //
        /////////////////////////////////////////////////////

        $("#cedVendedor").autocomplete({
            source: function (request, response) {
                var texto = $("#cedVendedor").val();
                debugger;
                console.log(texto);
                $.ajax({
                    type: "GET",
                    url: "/Vendedor/GetVendedorByName",
                    dataType: "json",
                    data: { name: texto },
                    success: function (data) {
                        response($.map(data, function (item) {
                            console.log(item.nombre);
                            //debugger;
                            return { label: item.nombre + " " + item.apellido, value: item.cedula };
                        }));
                    },
                    error: function (xhr, status, error) {
                        // xhr.requestText
                        // debugger;
                        alert("Error: " + error + ", No Error: " + xhr.status);
                    },
                });
            },
            select: function (event, ui) {


                $("#cedVendedor").val(ui.item.value);
                $("label[for*='IdVendedor']").html(ui.item.label)

                return false;
            }
        });
    </script>
}

Web/Views/Activo/Delete.cshtml
@model Infraestructure.Models.Activo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<div>
    <h4>Activo</h4>
    <hr />
    @using (Html.BeginForm("DeleteConfirmed", "Activo"))
    {
        @Html.AntiForgeryToken()

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.idActivo)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.idActivo)
        @Html.Hidden("id", Model.idActivo)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.descripcion)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.descripcion)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.numSerie)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.numSerie)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.modelo)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.modelo)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.vidaUtil)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.vidaUtil)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.fechaCompra)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.fechaCompra)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.precioColones)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.precioColones)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.precioDolares)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.precioDolares)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.fechaVenceGarantia)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.fechaVenceGarantia)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.fechaVenceSeguro)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.fechaVenceSeguro)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.estado)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.estado)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.fotoFactura)
    </dt>

    <dd>
        <input type="image" src="data:image/jpeg;charset=utf-8;base64,@Convert.ToBase64String(Model.fotoFactura)" id="ImagenFact" style="height:75px;width:75px">
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.fotoActivo)
    </dt>

    <dd>
        <input type="image" src="data:image/jpeg;charset=utf-8;base64,@Convert.ToBase64String(Model.fotoActivo)" id="ImagenAct" style="height:75px;width:75px">
    </dd>

    <dt>
        @Html.DisplayName("Asegurado")
    </dt>

    <dd>
        @{
            Html.RenderAction("GetAseguradoActById", "Asegurado", new { id = Model.idAsegurado });
        }
    </dd>

    <dt>
        @Html.DisplayName("Marca")
    </dt>

    <dd>
        @{
            Html.RenderAction("GetMarcaActById", "Marca", new { id = Model.idMarca });
        }
    </dd>

    <dt>
        @Html.DisplayName("Tipo de Activo")
    </dt>

    <dd>
        @{
            Html.RenderAction("GetTipoActById", "TipoActivo", new { id = Model.idTipoActivo });
        }
    </dd>

    <dt>
        @Html.DisplayName("Vendedor")
    </dt>

    <dd>
        @{
            Html.RenderAction("GetVendedorActById", "Vendedor", new { id = Model.cedVendedor });
        }
    </dd>

</dl>
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn  btn-danger btn-md " /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Web/Views/Activo/_DetalleActivo.cshtml
@model Infraestructure.Models.Activo

    <div>
        <h4>Activo</h4>
        
            @Html.DisplayFor(model => model.idActivo)
       
        <hr />
        <dl class="dl-horizontal">


            <dt>
                @Html.DisplayNameFor(model => model.descripcion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.descripcion)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.numSerie)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.numSerie)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.modelo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.modelo)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.vidaUtil)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.vidaUtil)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.fechaCompra)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.fechaCompra)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.precioColones)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.precioColones)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.precioDolares)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.precioDolares)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.fechaVenceGarantia)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.fechaVenceGarantia)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.fechaVenceSeguro)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.fechaVenceSeguro)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.estado)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.estado)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.fotoFactura)
            </dt>

            <dd>
                <input type="image" src="data:image/jpeg;charset=utf-8;base64,@Convert.ToBase64String(Model.fotoFactura)" id="ImagenFact" style="height:75px;width:75px">
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.fotoActivo)
            </dt>

            <dd>
                <input type="image" src="data:image/jpeg;charset=utf-8;base64,@Convert.ToBase64String(Model.fotoActivo)" id="ImagenAct" style="height:75px;width:75px">
            </dd>

            <dt>
                @Html.DisplayName("Asegurado")
            </dt>

            <dd>
                @{
                    Html.RenderAction("GetAseguradoActById", "Asegurado", new { id = Model.idAsegurado });
                }
            </dd>

            <dt>
                @Html.DisplayName("Marca")
            </dt>

            <dd>
                @{
                    Html.RenderAction("GetMarcaActById", "Marca", new { id = Model.idMarca });
                }
            </dd>

            <dt>
                @Html.DisplayName("Tipo de Activo")
            </dt>

            <dd>
                @{
                    Html.RenderAction("GetTipoActById", "TipoActivo", new { id = Model.idTipoActivo });
                }
            </dd>

            <dt>
                @Html.DisplayName("Vendedor")
            </dt>

            <dd>
                @{
                    Html.RenderAction("GetVendedorActById", "Vendedor", new { id = Model.cedVendedor });
                }
            </dd>

        </dl>
    </div>