Web/Controllers/ReportesController.cs
using ApplicationCore.Services;
using Infraestructure.Models;
using iText.IO.Font.Constants;
using iText.IO.Image;
using iText.Kernel.Colors;
using iText.Kernel.Font;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Web.Security;
using Web.Utils;
using Web.ViewModels;

namespace Web.Controllers
{
    public class ReportesController : Controller
    {
        // GET: Reportes
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Reporte)]
        public ActionResult ListaActivos()
        {
            IServiceActivo service = new ServiceActivo();
            IEnumerable<Activo> lista = service.GetActivo();
            return View(lista);
        }

        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Reporte)]
        public ActionResult CrearPDFActivos()
        {
            IEnumerable<Activo> lista = null;
            try
            {
                // Extraer informacion
                IServiceActivo _ServiceActivo = new ServiceActivo();
                lista = _ServiceActivo.GetActivo();

                // Crear stream para almacenar en memoria el reporte 
                MemoryStream ms = new MemoryStream();
                //Initialize writer
                PdfWriter writer = new PdfWriter(ms);

                //Inicia el document
                PdfDocument pdfDoc = new PdfDocument(writer);
                Document doc = new Document(pdfDoc);
                // Crea el header / Encabezado
                Paragraph header = new Paragraph("Lista de Activos")
                                   .SetFont(PdfFontFactory.CreateFont(StandardFonts.HELVETICA))
                                   .SetFontSize(14)
                                   .SetFontColor(ColorConstants.BLUE);
                // Agrega el Encabezado
                doc.Add(header);

                // Crear tabla con 16 columnas 
                Table table = new Table(6, true);
             
                // los Encabezados
                table.AddHeaderCell("Activo");
                table.AddHeaderCell("Modelo");
                table.AddHeaderCell("Marca");
               // table.AddHeaderCell("Tipo de Activo");
               // table.AddHeaderCell("Precio en colones");
               // table.AddHeaderCell("Precio en dolares");
                table.AddHeaderCell("Precio Actual");
                //  table.AddHeaderCell("Fecha de vencimiento de garantia");
                //  table.AddHeaderCell("Fecha de vencimiento de seguro");
              //  table.AddHeaderCell("Condición del activo");
               // table.AddHeaderCell("Asegurado");
                table.AddHeaderCell("Imagen del Activo");
                table.AddHeaderCell("Factura");

                IServiceTipoActivo serviceTpAct = new ServiceTipoActivo();
                IServiceMarca serviceMarca = new ServiceMarca();
                IServiceAsegurado serviceAsegurado = new ServiceAsegurado();

                foreach (var item in lista)
                {
                    // Agregar datos a las celdas
                    table.AddCell(new Paragraph(item.descripcion.ToString()));
                    table.AddCell(new Paragraph(item.modelo.ToString()));
                    Marca marca =serviceMarca.GetMarcaByID(item.idMarca);
                    table.AddCell(new Paragraph(marca.descripcion.ToString()));
                    //TipoActivo tipo = serviceTpAct.GetTipoActivoByID(item.idTipoActivo);
                   // table.AddCell(new Paragraph(tipo.descripcion.ToString()));
                  //  table.AddCell(new Paragraph(item.precioColones.ToString()));
                   // table.AddCell(new Paragraph(item.precioDolares.ToString()));
                    table.AddCell(new Paragraph(item.precioActual.ToString()));
                    // table.AddCell(new Paragraph(item.fechaVenceGarantia.ToString()));
                    //table.AddCell(new Paragraph(item.fechaVenceSeguro.ToString()));
                   // table.AddCell(new Paragraph(item.estado.ToString()));
                   // Asegurado asegurado = serviceAsegurado.GetAseguradoByID(item.idAsegurado);
                   // table.AddCell(new Paragraph(asegurado.descripcion.ToString()));

                    // Convierte la imagen que viene en Bytes en imagen para PDF
                    Image imageAct = new Image(ImageDataFactory.Create(item.fotoActivo));
                    // Tamaño de la imagen
                    imageAct = imageAct.SetHeight(75).SetWidth(75);
                    table.AddCell(imageAct);

                    Image imageFact = new Image(ImageDataFactory.Create(item.fotoFactura));
                    // Tamaño de la imagen
                    imageFact = imageFact.SetHeight(75).SetWidth(75);
                    table.AddCell(imageFact);
                    // table.SetFont(PdfFontFactory.CreateFont(StandardFonts.TIMES_ROMAN))
                    //     .SetFontSize(9);
                }
                doc.Add(table);

                // Calculo del monto total
                decimal montoTotal = (decimal)lista.ToList().Sum(k => k.precioActual);
                // Agrega  el monto total
                doc.Add(new Paragraph("\n\rMonto total de la depreciación de los activos: " + montoTotal.ToString("C", CultureInfo.CreateSpecificCulture("cr-CR"))));
                    
                /* doc.Add(new Paragraph("\n\rMonto total en dolares: " + montoTotalDolares.ToString(CultureInfo.CreateSpecificCulture("en-US"))))
                     .SetFont(PdfFontFactory.CreateFont(StandardFonts.TIMES_ROMAN))
                                    .SetFontSize(11);*/


                // Colocar número de páginas
               /* int numberOfPages = pdfDoc.GetNumberOfPages();
                for (int i = 1; i <= numberOfPages; i++)
                {

                    // Write aligned text to the specified by parameters point
                    doc.ShowTextAligned(new Paragraph(String.Format("pag {0} of {1}", i, numberOfPages)),
                            559, 826, i, TextAlignment.RIGHT, VerticalAlignment.TOP, 0);
                }*/


                //Close document
                doc.Close();

                // Retorna un File
                return File(ms.ToArray(), "application/pdf", "reporte");

            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Utils.Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }

        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Reporte)]
        public ActionResult ConsultaVenceGarantia()
        {
            return View();
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Reporte)]
        public ActionResult FiltarFechasGarantia(string txtFechaInicial, string txtFechaFinal)
        {
            try
            {
                if (txtFechaInicial == null || txtFechaFinal == null)
                {
                    TempData["Message"] = "Ingrese los datos determinados";
                    TempData.Keep();
                    return RedirectToAction("ConsultaVenceGarantia");
                }

                DateTime fechaI = DateTime.Parse(txtFechaInicial);
                DateTime fechaF = DateTime.Parse(txtFechaFinal);


                if (fechaI > fechaF)
                {
                    TempData["Message"] = "Sus datos no coinciden" ;
                    TempData.Keep();
                }

            IServiceActivo service = new ServiceActivo();
            IEnumerable<Activo> lista = service.GetActivoByDate(txtFechaInicial, txtFechaFinal);
                
                Log.Info("se realizo la consulta de fecha de vence garantia");

                //  return Json(lista, JsonRequestBehavior.AllowGet);
                return PartialView("_VenceGarantiaConsultado", lista);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Utils.Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }

        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Reporte)]
        public ActionResult IndexConsultarActivo()
        {
            return View();
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Reporte)]
        public ActionResult FiltrarActivo(int txtActivo)
        {
            try { 
            // Error porque viene en blanco 
            if (txtActivo<=0)
            {
                // Significa Error, va a ser capturado por onError del Javascript
                Response.StatusCode = -1;
                return View();
            }
           
            IServiceActivo serviceA = new ServiceActivo();
            Activo act = serviceA.GetActivoByID(txtActivo);
            IServiceDepreciacion serviceD = new ServiceDepreciacion();
            IEnumerable<HistorialDepreciacion> depreciacion = serviceD.GetDepreciacionByID(txtActivo);
            ViewDetalleActivoHistorial viewDetalle = new ViewDetalleActivoHistorial()
            {
                Activo = act,
                ListaDepreciacion = depreciacion,
            };
                Log.Info("se realizo la consulta de activo y depreciación");
            // Retorna un Partial View

Web/Views/Reportes/ConsultaVenceGarantia.cshtml
@{
    ViewBag.Title = "ConsultaVenceGarantia";
}

<h2 style="text-align:center">Consultar el vencimiento de la garantia de los activos</h2>
<br />
<br />
@using (Ajax.BeginForm("FiltarFechasGarantia", "Reportes", null, new AjaxOptions
{
    HttpMethod = "GET",
    OnFailure = "onFailureResult",
    UpdateTargetId = "resultado",
    InsertionMode = InsertionMode.Replace
}, new { id = "AjaxForm" }))
{

    if (TempData["Message"] != null)
    {
        string mensaje = @"<div class='alert alert-danger alert-dismissible' role='alert'>
<strong>Error!</strong> " + TempData["Message"] + "</div>";
@Html.Raw(mensaje);
}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <br />
                @Html.Label("Fecha Inicial")
                @Html.TextBox("txtFechaInicial", "01/01/2020", new { @class = "form-control", placeholder = "mm/dd/yyyy" })
            </div>
            <div class="form-group">
                @Html.Label("Fecha Final")
                @Html.TextBox("txtFechaFinal", "01/09/2020", new { @class = "form-control", placeholder = "mm/dd/yyyy" })
            </div>
            <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn  btn-success">Aceptar</button>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div id="resultado" />
        </div>
    </div>
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryajax")
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqueryui")

    <script type="text/javascript">

        // Evento que se ejecuta cuando la página esta cargada
        $(document).ready(function () {
            $('#txtFechaInicial').datepicker({
                dateFormat: "dd/mm/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0"
            });


            $('#txtFechaFinal').datepicker({
                dateFormat: "dd/mm/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0"
            });

        });
    </script>

    <script>
        var onFailureResult = function (err) {
            // Mostramos un mensaje de error.

            $("#ErrorAlert").show("slow");

        };
    </script>


}

Web/Views/Reportes/ConsultarCierreDepreciacion.cshtml
@{
    ViewBag.Title = "ConsultarCierreDepreciacion";
}

<h2>Consultar Cierre Depreciación</h2>

<br />
<br />
@using (Ajax.BeginForm("FiltrarCierre", "Reportes", null, new AjaxOptions
{
    HttpMethod = "GET",
    UpdateTargetId = "resultado",
    InsertionMode = InsertionMode.Replace
}, new { id = "AjaxForm" }))
{

    if (TempData["Message"] != null)
    {
        string mensaje = @"<div class='alert alert-danger alert-dismissible' role='alert'>
<strong>Error!</strong> " + TempData["Message"] + "</div>";
@Html.Raw(mensaje);
}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <br />
                @Html.Label("Fecha ")
                @Html.TextBox("txtFechaInicial", "01/01/2020", new { @class = "form-control", placeholder = "mm/dd/yyyy" })
            </div>

            <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn  btn-success">Aceptar</button>
                </div>
            </div>
        </div>
    </div>
    <br />
    <br />
    <div id="resultado" />
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryajax")
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqueryui")

    <script type="text/javascript">

        // Evento que se ejecuta cuando la página esta cargada
        $(document).ready(function () {
            $('#txtFechaInicial').datepicker({
                dateFormat: "dd/mm/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0"
            });
        });
    </script>
}

Web/Views/Reportes/IndexConsultarActivo.cshtml
@{
    ViewBag.Title = "IndexConsultarActivo";
}

<h2>Consultar Activo</h2>
@using (Ajax.BeginForm("FiltrarActivo", "Reportes", null, new AjaxOptions
{
    HttpMethod = "GET",
    OnFailure = "onFailureResult",
    UpdateTargetId = "resultado",
    InsertionMode = InsertionMode.Replace
}, new { id = "AjaxForm" }))
{
    <div class="form-horizontal">
        <div class="form-group">
            <div id='ErrorAlert' class='alert alert-danger' style="display:none" role='alert'>
                Se ha producito un error!
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                @Html.Label("Activo", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.TextBox("txtActivo", "", new { @class = "form-control" })
                @Html.Label("txtDescripcion", "-", htmlAttributes: new { @class = "control-label col-md-2" })
            </div>

        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn  btn-success">Aceptar</button>
            </div>
        </div>

    </div>
    <div id="resultado" />
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryajax")
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqueryui")

    <script>
        $("#txtActivo").focus(function () {
            // Limpia la caja de texto
            $("#txtActivo").val("");
            console.log($("label[for*='txtDescripcion']").html());
            $("label[for*='txtDescripcion']").html("-");
        });

        $("#txtActivo").autocomplete({
            source: function (request, response) {
                var texto = $("#txtActivo").val();
                debugger;
                console.log(texto);
                $.ajax({
                    type: "GET",
                    url: "/Activo/GetActivoByName",
                    dataType: "json",
                    data: { name: texto },
                    success: function (data) {
                        response($.map(data, function (item) {
                            console.log(item.descripcion);
                            //debugger;
                            return { label: item.descripcion, value: item.idActivo };
                        }));
                    },
                    error: function (xhr, status, error) {
                        // xhr.requestText
                        // debugger;
                        alert("Error: " + error + ", No Error: " + xhr.status);
                    },
                });
            },
            select: function (event, ui) {

                // Colocar el valor
                $("#txtActivo").val(ui.item.value);
                // Coloca datos en el Label
                $("label[for*='txtDescripcion']").html(ui.item.label);
                return false;
            }, statusCode: {
                404: function (content) { alert('cannot find resource'); },
                500: function (content) { alert('internal server error'); }
            },
            error: function (xhr, status, error) {
                // Muestra posibles errores
                alert("Error: " + error + ", No Error: " + xhr.status);
            }
        });
    </script>

    <!-- SE EJECUTA SI SE PRODUJO UN ERROR -->
    <script>
        var onFailureResult = function (err) {
            // Mostramos un mensaje de error.

            $("#ErrorAlert").show("slow");

        };
    </script>

}

Web/Views/Reportes/ListaActivos.cshtml
@model IEnumerable<Infraestructure.Models.Activo>

@{
    ViewBag.Title = "ListaActivos";
}

<h2>Lista de Activos</h2>

<p>
    @Html.ActionLink("Crear un PDF", "CrearPDFActivos")
</p>

<table class="table table-hover table-striped ">
    <tr>
        @*  <th>
            @Html.DisplayNameFor(model => model.idActivo)
        </th>
            <th>
            @Html.DisplayNameFor(model => model.numSerie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechaVenceGarantia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechaVenceSeguro)
        </th>
            <th>
            @Html.DisplayNameFor(model => model.fotoFactura)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.vidaUtil)
        </th>
            <th>
            @Html.DisplayNameFor(model => model.fechaCompra)
        </th>

        <th>
            @Html.DisplayName("Vendedor")
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.descripcion)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.modelo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.precioColones)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.precioDolares)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.precioActual)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.estado)
        </th>
        <th>
            @Html.DisplayName("Asegurado")
        </th>
        <th>
            @Html.DisplayName("Marca")
        </th>
        <th>
            @Html.DisplayName("Tipo de Activo")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fotoActivo)
        </th>

    </tr>

  @foreach (var item in Model)  {
<tr>
    @* <td>
            @Html.DisplayFor(modelItem => item.idActivo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.numSerie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fechaCompra)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fechaVenceGarantia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fechaVenceSeguro)
        </td>
        <td>
            <input type="image" src="data:image/jpeg;charset=utf-8;base64,@Convert.ToBase64String(item.fotoFactura)" id="ImagenFact" style="height:75px;width:75px">
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.vidaUtil)
        </td>
        <td>
            @{
                Html.RenderAction("GetVendedorActById", "Vendedor", new { id = item.cedVendedor });
            }
        </td>
    *@
    <td>
        @Html.DisplayFor(modelItem => item.descripcion)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.modelo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.precioColones)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.precioDolares)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.precioActual)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.estado)
    </td>
    <td>
        @{
            Html.RenderAction("GetAseguradoActById", "Asegurado", new { id = item.idAsegurado });
        }
    </td>
    <td>
        @{
            Html.RenderAction("GetMarcaActById", "Marca", new { id = item.idMarca });
        }
    </td>
    <td>
        @{
            Html.RenderAction("GetTipoActById", "TipoActivo", new { id = item.idTipoActivo });
        }
    </td>
    <td>
        <input type="image" src="data:image/jpeg;charset=utf-8;base64,@Convert.ToBase64String(item.fotoActivo)" id="ImagenFact" style="height:75px;width:75px">
    </td>

</tr>
   }

  </table>

Web/Views/Reportes/_ActivoConsultado.cshtml
@model Web.ViewModels.ViewDetalleActivoHistorial

<h2>Activo</h2>

<div class="row">
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayName("Foto del Activo")
            </dt>
            <dd>
                <input type="image" src="data:image/jpeg;charset=utf-8;base64,@Convert.ToBase64String(Model.Activo.fotoActivo)" style="height:150px;width:150px">
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Activo.descripcion)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Activo.descripcion)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Activo.fechaCompra)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Activo.fechaCompra)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Activo.precioColones)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Activo.precioColones)
            </dd>
            <dt>
                @Html.DisplayName("Factura")
            </dt>
            <dd>
                <input type="image" src="data:image/jpeg;charset=utf-8;base64,@Convert.ToBase64String(Model.Activo.fotoFactura)" style="height:150px;width:150px">
            </dd>
        </dl>
    </div>
   
    <div class="col-md-6">
        <table class="table table-hover table-striped ">
            <caption style="text-align:center;">Depreciación por periodo</caption>
            <tr>
                <th>
                    @Html.DisplayName("Fecha")
                </th>
                <th>
                    @Html.DisplayName("Precio actual")
                </th>
            </tr>

            @foreach (var item in Model.ListaDepreciacion)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Fecha)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.valor)
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

Web/Views/Reportes/_DetalleCierre.cshtml
@model IEnumerable<Infraestructure.Models.HistorialDepreciacion>


<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Activo")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.valor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @{
                    Html.RenderAction("GetActById", "Activo", new { id = item.idActivo });
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.valor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
        </tr>
    }
</table>
<div>
    <p>
        Monto total : @TempData["total"]
    </p>
</div>

Web/Views/Reportes/_VenceGarantiaConsultado.cshtml
@model IEnumerable<Infraestructure.Models.Activo>

<div class="form-group">
    <br>
    <table class="table table-hover table-striped ">
        <caption style="text-align:center">Fechas de vencimiento de Garantias</caption>
        <thead>
            <tr>
                <th>Activo</th>
                <th>Modelo</th>
                <th>Fecha</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>  @Html.DisplayFor(modelItem => item.descripcion)</td>
                <td>  @Html.DisplayFor(modelItem => item.modelo)</td>
                <td>  @Html.DisplayFor(modelItem => item.fechaVenceGarantia)</td>
            </tr>
            }
            </tbody>
    </table>
</div>